// This file is auto-generated by scripts/generate-collection-tools.mjs.
// Do not edit by hand.

export type CollectionDescriptor = {
  slug: string;
  source: string;
  hasSlugField: boolean;
  hasDrafts: boolean;
  hasUpload: boolean;
  toolSegment: string;
  skip?: boolean;
};

export const COLLECTIONS: CollectionDescriptor[] = [
  { slug: "caseStudies", source: "CaseStudies", hasSlugField: false, hasDrafts: false, hasUpload: false, toolSegment: "casestudies" },
  { slug: "categories", source: "Categories", hasSlugField: true, hasDrafts: false, hasUpload: false, toolSegment: "categories" },
  { slug: "customerLogos", source: "CustomerLogos", hasSlugField: false, hasDrafts: false, hasUpload: false, toolSegment: "customerlogos" },
  { slug: "docs", source: "Docs", hasSlugField: true, hasDrafts: false, hasUpload: false, toolSegment: "docs" },
  { slug: "landing", source: "Landing", hasSlugField: true, hasDrafts: true, hasUpload: false, toolSegment: "landing", skip: true },
  { slug: "landing-docs", source: "LandingDocs", hasSlugField: true, hasDrafts: false, hasUpload: false, toolSegment: "landing_docs" },
  { slug: "legal-docs", source: "LegalDocs", hasSlugField: false, hasDrafts: true, hasUpload: false, toolSegment: "legal_docs" },
  { slug: "media", source: "Media", hasSlugField: false, hasDrafts: false, hasUpload: true, toolSegment: "media" },
  { slug: "pages", source: "Pages", hasSlugField: true, hasDrafts: true, hasUpload: false, toolSegment: "pages" },
  { slug: "testimonials", source: "Testimonials", hasSlugField: false, hasDrafts: false, hasUpload: false, toolSegment: "testimonials" },
  { slug: "users", source: "Users", hasSlugField: false, hasDrafts: false, hasUpload: false, toolSegment: "users" },
];

export const SKIPPED_COLLECTIONS = COLLECTIONS.filter((c) => c.skip).map((c) => c.slug);
